### ISSUE TITLE
Cannot complete install wizard

### ISSUE THREAD

**Issue by dylanjacob** [Doptor-zz/Doptor#16]
After configuring the database and seeing that it can connect, and filling in admin user information, running the install results in an error "Class 'CreateCategoriesTable' not found".

This sounds a lot like #1 but it is still occuring.

**Comment by dakshhmehta** [comment]
Yes, I did reported to them. And It was fixed, but not sure why Its again. But yes, Its not working again!

**Comment by masud79** [comment]
You are requested download from www.github.com/Doptor/Doptor
Please let me know if still you are facing same problem.

**Comment by dylanjacob** [comment]
I did a clean install and I still have the problem.
1. Dropped all tables from database
2. Deleted the doptor folder
3. `git clone https://github.com/Doptor/Doptor.git doptor`
4. Configured Database from wizard (which confirmed it was able to reach the db)
5. Configured the admin user, timezone, etc.
6. Received the following error:

```
   Symfony \ Component \ Debug \ Exception \ FatalErrorException
   Class 'CreateCategoriesTable' not found
```

Upon checking the database, I have tables that were created, but no categories table exists.  I could be wrong here, but when dropping the tables in step 1 above, I recall there being a categories table.

**Comment by SubodhDahal** [comment]
It looks like the file `app\components\posts\database\migrations\2014_01_28_153951_create_categories_table.php` is currently empty. Until they fix it, you can copy, paste and save the following code in that file so that your problem will be solved.

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateCategoriesTable extends Migration {

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('categories', function(Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('alias');
            $table->string('type')->default('post');
            // $table->integer('language_id')->unsigned();
            $table->text('description')->nullable();
            $table->string('status', 20)->default('published');

            $table->integer('created_by')->unsigned();
            $table->integer('updated_by')->unsigned()->nullable();
            $table->timestamps();

            $table->index('created_by');
            $table->foreign('created_by')->references('id')->on('users')->on_delete('restrict')->on_update('cascade');

            $table->index('updated_by');
            $table->foreign('updated_by')->references('id')->on('users')->on_delete('restrict')->on_update('cascade');
        });
    }


    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('categories');
    }

}
```

**Comment by dylanjacob** [comment]
that fixed it!
